/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

dependencies {
    compileOnly(project(":acf-core"))
    compileOnly("com.mojang:brigadier:1.0.17")
}

description = "ACF (Brigadier)"
