/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "acf-parent"
include(":acf-bukkit")
include(":acf-jda")
include(":acf-paper")
include(":acf-velocity")
include(":acf-core")
include(":acf-sponge")
include(":acf-brigadier")
include(":acf-bungee")
project(":acf-bukkit").projectDir = file("bukkit")
project(":acf-jda").projectDir = file("jda")
project(":acf-paper").projectDir = file("paper")
project(":acf-velocity").projectDir = file("velocity")
project(":acf-core").projectDir = file("core")
project(":acf-sponge").projectDir = file("sponge")
project(":acf-brigadier").projectDir = file("brigadier")
project(":acf-bungee").projectDir = file("bungee")
