/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

dependencies {
    api(project(":acf-core"))
    compileOnly("net.dv8tion:JDA:4.2.0_168")
}

description = "ACF (JDA)"

tasks {
  processResources {
    from("${project.projectDir}/../languages/minecraft/")
  }
}
