/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

dependencies {
    implementation(project(":acf-core"))
    compileOnly("net.dv8tion:JDA:4.2.0_168")
}

description = "ACF (JDA)"
