/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

description = "ACF (Bukkit)"

dependencies {
    api(project(":acf-core"))
    implementation("co.aikar:minecraft-timings:1.0.4")
    compileOnly("org.bukkit:bukkit:1.12-R0.1-SNAPSHOT")
}

tasks {
  processResources {
    from("${project.projectDir}/../languages/minecraft/")
  }
}
