/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

dependencies {
    implementation(project(":acf-core"))
    compileOnly("net.md-5:bungeecord-api:1.13-SNAPSHOT")
}

description = "ACF (Bungee)"
