/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

dependencies {
    api(project(":acf-core"))
    compileOnly("net.md-5:bungeecord-api:1.14-SNAPSHOT")
}

description = "ACF (Bungee)"

tasks {
  processResources {
    from("${project.projectDir}/../languages/minecraft/")
  }
}
