/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

dependencies {
    api(project(":acf-bukkit"))
    api(project(":acf-brigadier"))
    compileOnly("com.destroystokyo.paper:paper-api:1.15.2-R0.1-SNAPSHOT")
    compileOnly("com.destroystokyo.paper:paper-mojangapi:1.15.2-R0.1-SNAPSHOT")
}

description = "ACF (Paper)"
