/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.aikar.java-conventions")
}

dependencies {
    api(project(":acf-core"))
    compileOnly("com.velocitypowered:velocity-api:1.0.0-SNAPSHOT")
}

description = "ACF (Velocity)"

tasks {
  processResources {
    from("${project.projectDir}/../languages/minecraft/")
  }
}
